### ISSUE TITLE
Some suggestions about LiveOPP

### ISSUE THREAD

**Issue by cocafe** [ChronoMonochrome/Chrono_Kernel-1#1]
Hi, just received some emails about the commits that mentions me.
And it's grand to see that someone is still developing for DB8500 chip.
I have some suggestions about LiveOPP I wrote years ago when I did not understand coding and linux too much.
In [liveopp_update_cpuhw()](https://github.com/ChronoMonochrome/Chrono_Kernel-1/blob/master/drivers/mfd/db8500-prcmu.c#L1698), maybe we should use spinlock here instead of mutex lock? Mutex lock will suspend/resume the thread which is acquiring the resource and spinlock will not, it's faster, maybe use some irq lock related spinlock.
And the mb(), it will tell the compiler not to optimize the code sequence above the mb(), so let it be one would be okay? Umm, I don't have a GT-I9070 around my hand right now, so I can't compile and test...

**Comment by cocafe** [comment]
Perhaps we don't need to lock here.
_drivers/cpufreq/dbx500-cpufreq.c_ calls set clock rate of "arm_clk".
And in _mach-ux500/clock-db8500.c_ we already have mutex lock here.
```
static struct clk clk_arm = {
	.name	= "arm_clk",
	.ops	= &clk_arm_ops,
	.mutex = &clk_arm_mutex,
	.cg_sel = PRCMU_ARMCLK,
};
// ...
static DEFINE_MUTEX(clk_arm_mutex);
```
_clk_arm_set_rate()_ calls prcmu to set clock rate.
Thus we don't need mutex lock in our liveopp arm_set function (unless it is called outside this fucntion chain)
Remove mutex_lock should reduce the time the function costs.
By the way, the other clock set functions called via sysfs should protect with locks, sysfs does not provide any rwlocks by default.

**Comment by ChronoMonochrome** [comment]
Thanks for ideas, I'll give a try!

**Comment by cocafe** [comment]
All right, happy coding

**Comment by cocafe** [comment]
Just read something about **memory barrier**, may be helpful.
Some referenece code in [msm-arch](https://github.com/cocafe/xperia_z2_kernel_cocore-l/blob/marshmallow/arch/arm/mach-msm/clock-krait.c#L157).
As we are configuring the hw by ourselves, we had to decide the delay time.
Compared to qualcomm platform, PRCMU should have some internal(in-chip) subroutines to adjust clock and voltage (so-called DVFS) (Just guessed from the documents) 
(ref: DM00030004_AP9500_reference_manual_rev1.pdf page.53)

**Comment by ChronoMonochrome** [comment]
Thanks for hints! I have removed the mutex from liveopp_cpuhw function and it seems to work fine :) However, I've not had a chance to run any stablilty benchmark test yet as I was busy with the kernel sources updates (I've just recently managed to  update kernel sources to android-3.4 and now fixing bugs that this update have introduced).

**Comment by ChronoMonochrome** [comment]
By the way, liveopp_cpuhw uses db8500_prcmu_writel function which turns in writel call, that in its turn calls mb() and writel_relaxed. So, if we are adding mb() calls by a hand, it's better then to use db8500_prcmu_writel_relaxed instead of db8500_prcmu_writel.

**Comment by cocafe** [comment]
Hmm, sounds reasonable.
